server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: file-manager
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres
    username: postgres.xmrsuhinbitsuwpncndq
    password: i5+cwb&wB7Srzjq
    driver-class-name: org.postgresql.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# JWT Configuration
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # a day
  refresh-token:
    expiration: 604800000 # 7 days


# File Storage Configuration
file:
  upload-dir: ./uploads
  download-url-expiration: 3600000 # 1 hour in milliseconds

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method 